/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:ae387dd3-6d7c-48a4-826c-b788462e12e0",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_cqAUPqltZ",
    "aws_user_pools_web_client_id": "7oo7ruu8p4c6j0ci5f6uf6vqf4",
    "oauth": {}
};


export default awsmobile;