name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - id: install
        uses: actions/setup-node@v1
        run: yarn install
      - id: lint
        uses: actions/setup-node@v1
        run: yarn lint

  test:

    runs-on: ubuntu-latest

    steps:
      - id: install
        uses: actions/setup-node@v1
        run: yarn install
      - id: test
        uses: actions/setup-node@v1
        run: yarn testFinal
