name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - id: setup
        uses: actions/checkout@v2
      - id: install
        run: yarn install
      - id: lint
        run: yarn lint

  test:

    runs-on: ubuntu-latest

    steps:
      - id: setup
        uses: actions/checkout@v2
      - id: install
        run: yarn install
      - id: test
        run: yarn testFinal
