name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
  lint:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: lint code
        run: yarn lint

  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test app
        run: yarn test
