name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: lint code
        run: yarn && yarn lint

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: test app
        run: yarn && yarn test
